services:
  api-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app
    ports:
      - "${API_1_HOST_PORT:-8080}:3000"
    environment:
      # Docker compose uses HOSTNAME as the container name
      # need to be unique for each container
      - INSTANCE_ID=${COMPOSE_PROJECT_NAME}-api-1

      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-inventory_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-inventory-updates}
      - SERVER_PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/health >/dev/null"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-migrator:
        condition: service_completed_successfully
    networks:
      - app-network
    restart: unless-stopped
  api-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app
    ports:
      - "${API_2_HOST_PORT:-8081}:3000"
    environment:
      # Docker compose uses HOSTNAME as the container name
      # need to be unique for each container
      - INSTANCE_ID=${COMPOSE_PROJECT_NAME}-api-2

      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-inventory_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-inventory-updates}
      - SERVER_PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/health >/dev/null"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-migrator:
        condition: service_completed_successfully
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:18.0
    ports:
      - "${DB_PORT:-15432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-inventory_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-inventory_db}",
        ]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:8.2.3
    ports:
      - "${REDIS_HOST_PORT:-16379}:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.0.1
    ports:
      - "${KAFKA_PORT:-19092}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1",
        ]

      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app-network
    restart: unless-stopped
  kafka-migrator:
    image: apache/kafka:4.0.1
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
    command:
      - sh
      - -lc
      - >
        set -e; BS="$$KAFKA_BROKERS"; [ -n "$$BS" ] || BS="kafka:9092"; TOPIC="inventory-updates"; if ! /opt/kafka/bin/kafka-topics.sh --bootstrap-server "$$BS" --list | grep -xq "$$TOPIC"; then
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server "$$BS" --create --topic "$$TOPIC" --partitions 1 --replication-factor 1;
        fi; echo "kafka topics ensured.";
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9094:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
    # depends_on:
    #   kafka:
    #     condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  kafka-data:
